---
deployment:
  tasks:
    - export DEPLOYPATH=/home/m1pmsbzqn4vh/public_html/
    - /bin/rm -rf ${DEPLOYPATH}assets
    - /bin/cp -R dist/assets ${DEPLOYPATH}assets
    - /bin/cp dist/index.html ${DEPLOYPATH}index.html
    - /bin/cp dist/favicon.svg ${DEPLOYPATH}favicon.svg
    - /bin/cp dist/icons.svg ${DEPLOYPATH}icons.svg
